// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TracePointAPI.Data;

#nullable disable

namespace TracePointAPI.Migrations
{
    [DbContext(typeof(TracePointContext))]
    partial class TracePointContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TracePointAPI.Models.Case", b =>
                {
                    b.Property<int>("CaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseID"));

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseID");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            CaseID = 1,
                            CaseName = "The Missing Prototype",
                            Description = "A technology company has reported that an experimental prototype disappeared from its research laboratory between 22:00 and 00:00. Only three employees had legitimate access to the area.",
                            Status = "Open"
                        });
                });

            modelBuilder.Entity("TracePointAPI.Models.Evidence", b =>
                {
                    b.Property<int>("EvidenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvidenceID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvidenceID");

                    b.ToTable("Evidence");

                    b.HasData(
                        new
                        {
                            EvidenceID = 1,
                            Description = "Jamie Smith's access card was used to enter the research laboratory at 23:41.",
                            Location = "Security Office",
                            Title = "Security Access Log"
                        },
                        new
                        {
                            EvidenceID = 2,
                            Description = "CCTV footage shows a person entering the laboratory at approximately 23:43. The person's face cannot be clearly identified.",
                            Location = "Research Laboratory",
                            Title = "CCTV Report"
                        },
                        new
                        {
                            EvidenceID = 3,
                            Description = "A partial fingerprint was found on the prototype storage cabinet. The fingerprint belongs to a person who regularly works in the laboratory.",
                            Location = "Research Laboratory",
                            Title = "Fingerprint Report"
                        },
                        new
                        {
                            EvidenceID = 4,
                            Description = "An email sent shortly before the incident states: \"The prototype must be moved before tomorrow's demonstration.\"",
                            Location = "Archive Room",
                            Title = "Email Message"
                        },
                        new
                        {
                            EvidenceID = 5,
                            Description = "A photograph taken after the incident shows that the prototype cabinet was open and the laboratory lights were switched off.",
                            Location = "Research Laboratory",
                            Title = "Photograph"
                        });
                });

            modelBuilder.Entity("TracePointAPI.Models.Investigation", b =>
                {
                    b.Property<int>("InvestigationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestigationID"));

                    b.Property<int>("CaseID")
                        .HasColumnType("int");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<int>("SuspectID")
                        .HasColumnType("int");

                    b.HasKey("InvestigationID");

                    b.HasIndex("CaseID");

                    b.HasIndex("SuspectID");

                    b.ToTable("Investigations");
                });

            modelBuilder.Entity("TracePointAPI.Models.Suspect", b =>
                {
                    b.Property<int>("SuspectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuspectID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuspectID");

                    b.ToTable("Suspects");

                    b.HasData(
                        new
                        {
                            SuspectID = 1,
                            Description = "Developed the software used by the prototype and had access to the laboratory.",
                            Name = "Alex Morgan",
                            Occupation = "Software Developer"
                        },
                        new
                        {
                            SuspectID = 2,
                            Description = "Responsible for security at the building on the night of the incident.",
                            Name = "Jamie Smith",
                            Occupation = "Security Officer"
                        },
                        new
                        {
                            SuspectID = 3,
                            Description = "Worked with the research team and had access to the laboratory during working hours.",
                            Name = "Taylor Williams",
                            Occupation = "Research Assistant"
                        });
                });

            modelBuilder.Entity("TracePointAPI.Models.Investigation", b =>
                {
                    b.HasOne("TracePointAPI.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TracePointAPI.Models.Suspect", "Suspect")
                        .WithMany()
                        .HasForeignKey("SuspectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Suspect");
                });
#pragma warning restore 612, 618
        }
    }
}
